// 主样式
export const styles = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    maxWidth: 1200,
    margin: '0 auto',
    padding: 20,
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  header: { textAlign: 'center', marginBottom: 20, color: '#fff' },
  title: { fontSize: 28, fontWeight: 'bold', margin: '10px 0', textShadow: '2px 2px 4px rgba(0,0,0,0.3)' },
  subtitle: { fontSize: 14, opacity: 0.9 },
  center: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100vh', background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  spinner: { width: 50, height: 50, border: '4px solid rgba(255,255,255,0.3)', borderTop: '4px solid #fff', borderRadius: '50%', animation: 'spin 1s linear infinite' },
  filterContainer: { backgroundColor: 'rgba(255,255,255,0.95)', borderRadius: 12, padding: 15, marginBottom: 15 },
  searchContainer: { display: 'flex', alignItems: 'center', marginBottom: 10 },
  searchInput: { flex: 1, padding: '12px 15px', fontSize: 16, border: '2px solid #e0e0e0', borderRadius: 8 },
  clearButton: { marginLeft: 10, padding: '10px 15px', backgroundColor: '#ff5252', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer' },
  filterRow: { display: 'flex', flexWrap: 'wrap', gap: 15, alignItems: 'center' },
  filterItem: { display: 'flex', alignItems: 'center', gap: 8 },
  filterLabel: { fontSize: 14, fontWeight: 'bold', color: '#333' },
  filterSelect: { padding: '8px 12px', fontSize: 14, border: '2px solid #e0e0e0', borderRadius: 8, cursor: 'pointer' },
  checkboxLabel: { display: 'flex', alignItems: 'center', gap: 5, fontSize: 14, cursor: 'pointer' },
  resultCount: { textAlign: 'center', color: '#666', marginTop: 10, fontSize: 14 },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 15 },
  card: { backgroundColor: 'rgba(255,255,255,0.95)', borderRadius: 12, padding: 15, textAlign: 'center', cursor: 'pointer', position: 'relative' },
  cardImage: { width: 120, height: 120, objectFit: 'contain' },
  cardId: { fontSize: 12, color: '#666', margin: '5px 0' },
  cardNameZh: { fontSize: 16, fontWeight: 'bold', color: '#333', margin: '5px 0 2px 0' },
  cardNameEn: { fontSize: 12, color: '#666', margin: '0 0 3px 0', textTransform: 'capitalize' },
  cardTypes: { display: 'flex', justifyContent: 'center', gap: 5, marginTop: 8 },
  cardTypeBadge: { padding: '3px 8px', borderRadius: 10, color: '#fff', fontSize: 11, fontWeight: 'bold' },
  favoriteButton: { position: 'absolute', top: 10, right: 10, background: 'rgba(255,255,255,0.8)', border: 'none', borderRadius: '50%', padding: 5, cursor: 'pointer' },
  noResults: { textAlign: 'center', color: '#fff', padding: 40 },
  pagination: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 20, marginTop: 20 },

  pageButton: { padding: '10px 20px', backgroundColor: 'rgba(255,255,255,0.9)', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14 },
  pageInfo: { color: '#fff', fontSize: 14 },
  backButton: { padding: '10px 20px', backgroundColor: 'rgba(255,255,255,0.2)', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer' },
  compareButton: { padding: '10px 16px', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14, fontWeight: 'bold', transition: 'background-color 0.2s' },
  viewCompareButton: { padding: '10px 16px', backgroundColor: '#f59e0b', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14, fontWeight: 'bold', transition: 'background-color 0.2s' },
  detailContent: { display: 'flex', gap: 30, backgroundColor: 'rgba(255,255,255,0.95)', borderRadius: 12, padding: 30 },
  detailImage: { width: 250, height: 250, objectFit: 'contain' },
  detailInfo: { flex: 1 },
  typeBadges: { display: 'flex', gap: 10, marginBottom: 20 },
  typeBadge: { padding: '8px 16px', borderRadius: 15, color: '#fff', fontSize: 14, fontWeight: 'bold' },
  infoRow: { display: 'flex', gap: 30, fontSize: 14, color: '#666' },
  abilitiesSection: { marginTop: 20 },
  abilitiesTitle: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 10 },
  abilitiesList: { display: 'flex', flexDirection: 'column', gap: 8 },
  abilityBadge: {
    padding: '6px 14px',
    borderRadius: 20,
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  hiddenTag: { fontSize: 11, opacity: 0.9 },
  statsSection: {
    marginTop: 20,
  },
  statsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  radarChartContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 15,
    backgroundColor: 'rgba(0, 0, 0, 0.02)',
    borderRadius: 12,
    padding: 10,
  },
  statsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  statRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  statName: {
    width: 50,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#555',
  },
  statBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  statBar: {
    height: '100%',
    borderRadius: 4,
    transition: 'width 0.3s ease',
  },
  statValue: {
    width: 30,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'right',
  },
  evolutionSection: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 12,
    padding: '20px 30px',
    marginTop: 20,
  },
  evolutionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  evolutionLoading: {
    textAlign: 'center',
    color: '#666',
    fontSize: 14,
    padding: '20px 0',
  },
  evolutionChain: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  evolutionItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.03)',
    transition: 'transform 0.2s, opacity 0.2s',
    minWidth: 100,
  },
  evolutionImage: {
    width: 80,
    height: 80,
    objectFit: 'contain',
  },
  evolutionName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
    margin: '5px 0 2px',
    textTransform: 'capitalize',
  },
  evolutionId: {
    fontSize: 10,
    color: '#999',
    margin: 0,
  },
  evolutionArrow: {
    fontSize: 24,
    color: '#666',
    fontWeight: 'bold',
    margin: '0 5px',
  },
  typeChartButton: {
    padding: '8px 16px',
    backgroundColor: '#8b5cf6',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 'bold',
    transition: 'background-color 0.2s',
  },
};

// 弹窗样式
export const modalStyles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    maxWidth: 500,
    width: '90%',
    maxHeight: '80vh',
    overflow: 'hidden',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid #e5e7eb',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    margin: 0,
  },
  closeBtn: {
    background: 'rgba(255,255,255,0.2)',
    border: 'none',
    borderRadius: '50%',
    width: 30,
    height: 30,
    cursor: 'pointer',
    fontSize: 16,
    color: '#fff',
  },
  content: {
    padding: 20,
  },
  selectRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  select: {
    padding: '10px 15px',
    fontSize: 14,
    border: '2px solid #e0e0e0',
    borderRadius: 8,
    cursor: 'pointer',
    minWidth: 120,
  },
  tableWrapper: {
    maxHeight: 400,
    overflowY: 'auto',
    borderRadius: 8,
    border: '1px solid #e5e7eb',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '12px 16px',
    textAlign: 'left',
    backgroundColor: '#f3f4f6',
    fontWeight: 'bold',
    fontSize: 14,
    color: '#374151',
    position: 'sticky',
    top: 0,
  },
  td: {
    padding: '10px 16px',
    borderBottom: '1px solid #e5e7eb',
  },
  typeBadge: {
    display: 'inline-block',
    padding: '4px 12px',
    borderRadius: 12,
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  effectCell: {
    textAlign: 'center',
  },
  effectBadge: {
    display: 'inline-block',
    padding: '6px 12px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 'bold',
    minWidth: 80,
    textAlign: 'center',
  },
};

// 对比页样式
export const compareStyles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    padding: 20,
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: 20,
    maxWidth: 900,
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 25px 80px rgba(0, 0, 0, 0.5)',
  },
  loading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 60,
  },
  title: {
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    margin: 0,
    padding: '20px 20px 15px',
    borderBottom: '1px solid #e5e7eb',
  },
  compareContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: '20px 30px',
    gap: 10,
    borderBottom: '1px solid #e5e7eb',
  },
  pokemonSide: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: 15,
  },
  pokemonImage: {
    width: 180,
    height: 180,
    objectFit: 'contain',
  },
  pokemonName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    margin: '10px 0 8px',
    textTransform: 'capitalize',
  },
  typeBadges: {
    display: 'flex',
    gap: 8,
    marginBottom: 12,
  },
  typeBadge: {
    padding: '4px 12px',
    borderRadius: 12,
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  infoRow: {
    display: 'flex',
    gap: 20,
    fontSize: 13,
    color: '#666',
  },
  vsContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 15px',
  },
  vsText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ef4444',
    textShadow: '2px 2px 4px rgba(0,0,0,0.2)',
  },
  statsSection: {
    padding: '20px 30px',
  },
  statsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  statRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: 12,
  },
  statLabel: {
    width: 50,
    textAlign: 'center',
  },
  statValueLeft: (isWinner) => ({
    fontSize: 16,
    fontWeight: isWinner ? 'bold' : 'normal',
    color: isWinner ? '#22c55e' : '#374151',
  }),
  statValueRight: (isWinner) => ({
    fontSize: 16,
    fontWeight: isWinner ? 'bold' : 'normal',
    color: isWinner ? '#22c55e' : '#374151',
  }),
  statBarsContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  statNameCenter: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#6b7280',
    marginBottom: 4,
  },
  statBarsRow: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    gap: 8,
  },
  statBarWrapper: {
    flex: 1,
    height: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    borderRadius: 6,
    overflow: 'hidden',
    display: 'flex',
  },
  statBarLeft: {
    height: '100%',
    borderRadius: '6px 0 0 6px',
    marginRight: 'auto',
    transition: 'width 0.3s ease',
  },
  statBarRight: {
    height: '100%',
    borderRadius: '0 6px 6px 0',
    marginLeft: 'auto',
    transition: 'width 0.3s ease',
  },
  footer: {
    display: 'flex',
    justifyContent: 'center',
    padding: '15px 20px 25px',
    borderTop: '1px solid #e5e7eb',
  },
  closeButton: {
    padding: '12px 40px',
    backgroundColor: '#6366f1',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    fontSize: 16,
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background-color 0.2s, transform 0.1s',
  },
};